"use client";

import { Layout } from "@/Layouts";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/Redux/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>JAMBO</title>
      </head>
      <body>
        <Provider store={store}>
          <Layout>{children}</Layout>
        </Provider>
      </body>
    </html>
  );
}
