"use client";

import { Layout } from "@/Layouts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Nav = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <nav>Header</nav>
      {children}
    </>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
